### ISSUE TITLE
[FEATURE] Amélioration du tracking

### ISSUE THREAD

**Issue by Drosscend** [Drosscend/MiniBox#44]
### Détail de contact

Drosscend#6715

### Description

Utilisation de : https://github.com/tryolabs/norfair

- [x] Tracking fonctionnel avec yolov5
- [x] Remplacement de l'ancien tracking
- [x] Mise à jour du code
- [x] Mise à jour des tests
- [x] Mise à jour des docs
- [x] Meilleure sauvegarde dans le fichier CSV
- [x] Possibilité d'enregistrer plusieurs classes

Infos sur la sauvegarde dans le CSV :
1 enregistrement par minutes (paramétrables) (donc 1 lignes par minute)
- le nombre totale d'objets détecté
- le nombre totale d'objets qui va vers le top-left
- le nombre totale d'objets qui va vers le top-right
- le nombre totale d'objets qui va vers le bottom-left
- le nombre totale d'objets qui va vers le bottom-right

### Code of Conduct

- [X] J'ai lu et j'accepte le Code de conduite.
